### ISSUE TITLE
Docker Build Error

### ISSUE THREAD

**Issue by matt-lethargic** [ChHarding/TouchTerrain_jupyter_docker#5]
When trying to docker build I get an error. (I'm a C# dev so no idea whats going on here unless its just `libsqlite3-0` missing)

Line
`ERROR [22/30] RUN mamba install jupyter_contrib_nbextensions -y -c conda-forge`

Error
```
#25 36.44 Traceback (most recent call last):
#25 36.44   File "<string>", line 1, in <module>
#25 36.44   File "/usr/local/lib/python3.10/site-packages/notebook/nbextensions.py", line 203, in install_nbextension_python
#25 36.44     m, nbexts = _get_nbextension_metadata(module)
#25 36.44   File "/usr/local/lib/python3.10/site-packages/notebook/nbextensions.py", line 1107, in _get_nbextension_metadata
#25 36.44     m = import_item(module)
#25 36.44   File "/usr/local/lib/python3.10/site-packages/traitlets/utils/importstring.py", line 38, in import_item
#25 36.44     return __import__(parts[0])
#25 36.44   File "/usr/local/lib/python3.10/site-packages/latex_envs/__init__.py", line 3, in <module>
#25 36.44     from . import latex_envs
#25 36.44   File "/usr/local/lib/python3.10/site-packages/latex_envs/latex_envs.py", line 19, in <module>
#25 36.44     from IPython.display import HTML, display,JSON
#25 36.44   File "/usr/local/lib/python3.10/site-packages/IPython/__init__.py", line 52, in <module>
#25 36.44     from .terminal.embed import embed
#25 36.44   File "/usr/local/lib/python3.10/site-packages/IPython/terminal/embed.py", line 15, in <module>
#25 36.44     from IPython.core.interactiveshell import DummyMod, InteractiveShell
#25 36.44   File "/usr/local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 73, in <module>
#25 36.44     from IPython.core.history import HistoryManager
#25 36.44   File "/usr/local/lib/python3.10/site-packages/IPython/core/history.py", line 11, in <module>
#25 36.44     import sqlite3
#25 36.44   File "/usr/local/lib/python3.10/sqlite3/__init__.py", line 57, in <module>
#25 36.44     from sqlite3.dbapi2 import *
#25 36.44   File "/usr/local/lib/python3.10/sqlite3/dbapi2.py", line 27, in <module>
#25 36.44     from _sqlite3 import *
#25 36.44 ImportError: libsqlite3.so.0: cannot open shared object file: No such file or directory
#25 36.44
#25 36.44 Enabling: jupyter_nbextensions_configurator
#25 36.44 - Writing config: /usr/local/etc/jupyter
#25 36.44     - Validating...
#25 36.44       jupyter_nbextensions_configurator 0.4.1 OK
#25 36.44 Enabling notebook nbextension nbextensions_configurator/config_menu/main...
#25 36.44 Enabling tree nbextension nbextensions_configurator/tree_tab/main...
#25 36.44
#25 36.44 Traceback (most recent call last):
#25 36.44   File "/usr/local/lib/python3.10/site-packages/notebook/services/sessions/sessionmanager.py", line 9, in <module>
#25 36.44     import sqlite3
#25 36.44   File "/usr/local/lib/python3.10/sqlite3/__init__.py", line 57, in <module>
#25 36.44     from sqlite3.dbapi2 import *
#25 36.44   File "/usr/local/lib/python3.10/sqlite3/dbapi2.py", line 27, in <module>
#25 36.44     from _sqlite3 import *
#25 36.44 ImportError: libsqlite3.so.0: cannot open shared object file: No such file or directory
#25 36.44
#25 36.44 During handling of the above exception, another exception occurred:
#25 36.44
#25 36.44 Traceback (most recent call last):
#25 36.44   File "/usr/local/bin/jupyter-contrib-nbextension", line 6, in <module>
#25 36.44     from jupyter_contrib_nbextensions.application import main
#25 36.44   File "/usr/local/lib/python3.10/site-packages/jupyter_contrib_nbextensions/application.py", line 13, in <module>
#25 36.44     from jupyter_contrib_nbextensions.install import (
#25 36.44   File "/usr/local/lib/python3.10/site-packages/jupyter_contrib_nbextensions/install.py", line 12, in <module>
#25 36.44     from notebook.notebookapp import list_running_servers
#25 36.44   File "/usr/local/lib/python3.10/site-packages/notebook/notebookapp.py", line 83, in <module>
#25 36.44     from .services.sessions.sessionmanager import SessionManager
#25 36.44   File "/usr/local/lib/python3.10/site-packages/notebook/services/sessions/sessionmanager.py", line 12, in <module>
#25 36.44     from pysqlite2 import dbapi2 as sqlite3
#25 36.44 ModuleNotFoundError: No module named 'pysqlite2'
#25 36.44
#25 36.44 done
#25 36.44 ERROR conda.core.link:_execute(733): An error occurred while installing package 'conda-forge::jupyter_latex_envs-1.4.6-pyhd8ed1ab_1002'.
#25 36.44 Rolling back transaction: ...working... done
#25 36.51 post-link script failed for package conda-forge::jupyter_latex_envs-1.4.6-pyhd8ed1ab_1002
#25 36.51 location of failed script: /usr/local/bin/.jupyter_latex_envs-post-link.sh
#25 36.51 ==> script messages <==
#25 36.51 Traceback (most recent call last):
#25 36.51   File "<string>", line 1, in <module>
#25 36.51   File "/usr/local/lib/python3.10/site-packages/notebook/nbextensions.py", line 203, in install_nbextension_python
#25 36.51     m, nbexts = _get_nbextension_metadata(module)
#25 36.51   File "/usr/local/lib/python3.10/site-packages/notebook/nbextensions.py", line 1107, in _get_nbextension_metadata
#25 36.51     m = import_item(module)
#25 36.51   File "/usr/local/lib/python3.10/site-packages/traitlets/utils/importstring.py", line 38, in import_item
#25 36.51     return __import__(parts[0])
#25 36.51   File "/usr/local/lib/python3.10/site-packages/latex_envs/__init__.py", line 3, in <module>
#25 36.51     from . import latex_envs
#25 36.51   File "/usr/local/lib/python3.10/site-packages/latex_envs/latex_envs.py", line 19, in <module>
#25 36.51     from IPython.display import HTML, display,JSON
#25 36.51   File "/usr/local/lib/python3.10/site-packages/IPython/__init__.py", line 52, in <module>
#25 36.51     from .terminal.embed import embed
#25 36.51   File "/usr/local/lib/python3.10/site-packages/IPython/terminal/embed.py", line 15, in <module>
#25 36.51     from IPython.core.interactiveshell import DummyMod, InteractiveShell
#25 36.51   File "/usr/local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 73, in <module>
#25 36.51     from IPython.core.history import HistoryManager
#25 36.51   File "/usr/local/lib/python3.10/site-packages/IPython/core/history.py", line 11, in <module>
#25 36.51     import sqlite3
#25 36.51   File "/usr/local/lib/python3.10/sqlite3/__init__.py", line 57, in <module>
#25 36.51     from sqlite3.dbapi2 import *
#25 36.51   File "/usr/local/lib/python3.10/sqlite3/dbapi2.py", line 27, in <module>
#25 36.51     from _sqlite3 import *
#25 36.51 ImportError: libsqlite3.so.0: cannot open shared object file: No such file or directory
#25 36.51
#25 36.51 ==> script output <==
#25 36.51 stdout:
#25 36.51 stderr:
#25 36.51 return code: 1
#25 36.51
#25 36.51 ()
#25 36.51
#25 36.51
#25 36.51 LinkError: post-link script failed for package conda-forge::jupyter_latex_envs-1.4.6-pyhd8ed1ab_1002
#25 36.51 location of failed script: /usr/local/bin/.jupyter_latex_envs-post-link.sh
#25 36.51 ==> script messages <==
#25 36.51 Traceback (most recent call last):
#25 36.51   File "<string>", line 1, in <module>
#25 36.51   File "/usr/local/lib/python3.10/site-packages/notebook/nbextensions.py", line 203, in install_nbextension_python
#25 36.51     m, nbexts = _get_nbextension_metadata(module)
#25 36.51   File "/usr/local/lib/python3.10/site-packages/notebook/nbextensions.py", line 1107, in _get_nbextension_metadata
#25 36.51     m = import_item(module)
#25 36.51   File "/usr/local/lib/python3.10/site-packages/traitlets/utils/importstring.py", line 38, in import_item
#25 36.51     return __import__(parts[0])
#25 36.51   File "/usr/local/lib/python3.10/site-packages/latex_envs/__init__.py", line 3, in <module>
#25 36.51     from . import latex_envs
#25 36.51   File "/usr/local/lib/python3.10/site-packages/latex_envs/latex_envs.py", line 19, in <module>
#25 36.51     from IPython.display import HTML, display,JSON
#25 36.51   File "/usr/local/lib/python3.10/site-packages/IPython/__init__.py", line 52, in <module>
#25 36.51     from .terminal.embed import embed
#25 36.51   File "/usr/local/lib/python3.10/site-packages/IPython/terminal/embed.py", line 15, in <module>
#25 36.51     from IPython.core.interactiveshell import DummyMod, InteractiveShell
#25 36.51   File "/usr/local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 73, in <module>
#25 36.51     from IPython.core.history import HistoryManager
#25 36.51   File "/usr/local/lib/python3.10/site-packages/IPython/core/history.py", line 11, in <module>
#25 36.51     import sqlite3
#25 36.51   File "/usr/local/lib/python3.10/sqlite3/__init__.py", line 57, in <module>
#25 36.51     from sqlite3.dbapi2 import *
#25 36.51   File "/usr/local/lib/python3.10/sqlite3/dbapi2.py", line 27, in <module>
#25 36.51     from _sqlite3 import *
#25 36.51 ImportError: libsqlite3.so.0: cannot open shared object file: No such file or directory
#25 36.51
#25 36.51 ==> script output <==
#25 36.51 stdout:
#25 36.51 stderr:
#25 36.51 return code: 1
#25 36.51
#25 36.51 ()
#25 36.51
```

**Comment by matt-lethargic** [comment]
I think I just fixed by moving 

```
# Here you can put some missing packages
RUN apt-get update && apt-get install -y \
    build-essential \
    vim \
&& rm -rf /var/lib/apt/lists/*
```

to circa line 7 of the Dockerfile
